version: "3.8"
services:
  frontend:
    image: 471112925329.dkr.ecr.eu-west-3.amazonaws.com/frontend-devops-ecr
    container_name: frontend
    restart: always
    environment:
      NODE_ENV: prod

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - /home/ec2-user/app/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend