version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: eu-west-3
    ACCOUNT_ID: '471112925329'
    REPOSITORY_NAME: frontend-devops-ecr
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPOSITORY_NAME

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd frontend
      - ls -la
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker images
      - docker push $REPOSITORY_URI:$IMAGE_TAG